const translations = {
    en: {
        services: "Services",
        contact: "Contact",
        njPortal: "NJ Portal",
        prudentClientDesk: "Prudent Client Desk",
        fundzBazzarPortal: "FundzBazzar Portal",
        amfiindia: "Amfiindia",
        welcomeToRekmand: "Welcome to Rekmand",
        professionalMutualFundManagement: "Professional Mutual Fund Management",
        expertMutualFundManagement: "Expert mutual fund management with personalized service",
        exploreMutualFunds: "Explore Mutual Funds",
        startInvestingToday: "Start Investing Today",
        marketOverview: "Market Overview",
        nifty50: "Nifty 50",
        sensex: "Sensex",
        niftyMidcap50: "Nifty Midcap 50",
        dataDelayNote: "Data may have a delay of 5min. For correct data, please refer to BSE/NSE webpage.",
        top3MutualFunds: "Top 3 Mutual Funds",
        investmentTools: "Investment Tools",
        sipCalculator: "SIP Calculator",
        lumpsumCalculator: "Lumpsum Calculator",
        riskProfiler: "Risk Profiler",
        goalPlanning: "Goal Planning",
        calculate: "Calculate",
        ourServices: "Our Services",
        portfolioManagement: "Portfolio Management",
        mutualFundInvestment: "Mutual Fund Investment",
        financialPlanning: "Financial Planning",
        personalizedAdvisory: "Personalized Advisory",
        faq: "Frequently Asked Questions",
        whatIsMutualFund: "What is a Mutual Fund?",
        howToStartInvesting: "How do I start investing with Rekmand?",
        risksInvolved: "What are the risks involved in mutual fund investments?",
        personalizedFinancialPlanning: "Do you offer personalized financial planning?",
        getInTouch: "Get in Touch",
        contactInformation: "Contact Information",
        physicalAddressComingSoon: "Physical address coming soon",
        mapIntegrationComingSoon: "Map integration coming soon",
        contactForm: "Contact Form",
        name: "Name",
        contactNumber: "Contact Number",
        subject: "Subject",
        message: "Message",
        sendMessage: "Send Message",
        allRightsReserved: "All rights reserved.",
        language: "Language",
        rekmandName: "Rekmand",
        njEWealth: "NJ E-Wealth",
        njClientDesk: "NJ Client Desk",
        fundzBazzarSignin: "FundzBazzar Signin",
        fundzBazzarBroking: "FundzBazzar Broking",
        keywords: "Mutual Fund, Investment, Portfolio Management, Financial Planning, Rekmand",
        sipCalculatorDescription: "Estimate your returns from monthly SIP investments.",
        lumpsumCalculatorDescription: "Calculate future value of a one-time investment.",
        riskProfilerDescription: "Assess your risk profile for better investment decisions.",
        goalPlanningDescription: "Plan and track your financial goals with ease.",
        portfolioManagementDescription: "Customized portfolio strategies to help you achieve your financial goals.",
        mutualFundInvestmentDescription: "Expert guidance for investing in top-performing mutual funds.",
        financialPlanningDescription: "Comprehensive financial planning for a secure future.",
        personalizedAdvisoryDescription: "One-on-one advisory to help you make informed investment decisions.",
        whatIsMutualFundDescription: "A mutual fund is a professionally managed investment fund that pools money from many investors to purchase securities.",
        howToStartInvestingDescription: "Starting your investment journey with Rekmand is simple. Contact us through the form on this page or by phone/email to schedule a consultation.",
        risksInvolvedDescription: "All mutual fund investments are subject to market risks. It's important to read all scheme related documents carefully.",
        personalizedFinancialPlanningDescription: "Yes, we offer comprehensive and personalized financial planning services to help you achieve your financial objectives.",
        yourNamePlaceholder: "Your Name",
        yourContactNumberPlaceholder: "Your Contact Number",
        subjectOfYourMessagePlaceholder: "Subject of your message",
        howCanWeHelpYouPlaceholder: "How can we help you?"
    },
    hi: {
        services: "सेवाएं",
        contact: "संपर्क करें",
        njPortal: "एनजे पोर्टल",
        prudentClientDesk: "प्रूडेंट क्लाइंट डेस्क",
        fundzBazzarPortal: "फंड्ज़बाज़ार पोर्टल",
        amfiindia: "एम्फीइंडिया",
        welcomeToRekmand: "रेकमंड में आपका स्वागत है",
        professionalMutualFundManagement: "पेशेवर म्यूचुअल फंड प्रबंधन",
        expertMutualFundManagement: "व्यक्तिगत सेवा के साथ विशेषज्ञ म्यूचुअल फंड प्रबंधन",
        exploreMutualFunds: "म्यूचुअल फंड खोजें",
        startInvestingToday: "आज ही निवेश करना शुरू करें",
        marketOverview: "बाजार अवलोकन",
        nifty50: "निफ्टी 50",
        sensex: "सेंसेक्स",
        niftyMidcap50: "निफ्टी मिडकैप 50",
        dataDelayNote: "डेटा में 5 मिनट की देरी हो सकती है। सही डेटा के लिए, कृपया बीएसई/एनएसई वेबपेज देखें।",
        top3MutualFunds: "शीर्ष 3 म्यूचुअल फंड",
        investmentTools: "निवेश उपकरण",
        sipCalculator: "एसआईपी कैलकुलेटर",
        lumpsumCalculator: "एकमुश्त कैलकुलेटर",
        riskProfiler: "जोखिम प्रोफाइलर",
        goalPlanning: "लक्ष्य योजना",
        calculate: "गणना करें",
        ourServices: "हमारी सेवाएं",
        portfolioManagement: "पोर्टफोलियो प्रबंधन",
        mutualFundInvestment: "म्यूचुअल फंड निवेश",
        financialPlanning: "वित्तीय योजना",
        personalizedAdvisory: "व्यक्तिगत सलाह",
        faq: "अक्सर पूछे जाने वाले प्रश्न",
        whatIsMutualFund: "म्यूचुअल फंड क्या है?",
        howToStartInvesting: "रेकमंड के साथ निवेश कैसे शुरू करें?",
        risksInvolved: "म्यूचुअल फंड निवेश में शामिल जोखिम क्या हैं?",
        personalizedFinancialPlanning: "क्या आप व्यक्तिगत वित्तीय योजना प्रदान करते हैं?",
        getInTouch: "संपर्क करें",
        contactInformation: "संपर्क जानकारी",
        physicalAddressComingSoon: "भौतिक पता जल्द आ रहा है",
        mapIntegrationComingSoon: "मानचित्र एकीकरण जल्द आ रहा है",
        contactForm: "संपर्क फ़ॉर्म",
        name: "नाम",
        contactNumber: "संपर्क नंबर",
        subject: "विषय",
        message: "संदेश",
        sendMessage: "संदेश भेजें",
        allRightsReserved: "सर्वाधिकार सुरक्षित।",
        language: "भाषा",
        rekmandName: "रेकमंड",
        njEWealth: "एनजे ई-वेल्थ",
        njClientDesk: "एनजे क्लाइंट डेस्क",
        fundzBazzarSignin: "फंड्ज़बाज़ार साइनइन",
        fundzBazzarBroking: "फंड्ज़बाज़ार ब्रोकिंग",
        keywords: "म्यूचुअल फंड, निवेश, पोर्टफोलियो प्रबंधन, वित्तीय योजना, रेकमंड",
        sipCalculatorDescription: "मासिक एसआईपी निवेश से अपने रिटर्न का अनुमान लगाएं।",
        lumpsumCalculatorDescription: "एकमुश्त निवेश के भविष्य के मूल्य की गणना करें।",
        riskProfilerDescription: "बेहतर निवेश निर्णयों के लिए अपनी जोखिम प्रोफ़ाइल का आकलन करें।",
        goalPlanningDescription: "आसानी से अपने वित्तीय लक्ष्यों की योजना बनाएं और ट्रैक करें।",
        portfolioManagementDescription: "आपके वित्तीय लक्ष्यों को प्राप्त करने में मदद करने के लिए अनुकूलित पोर्टफोलियो रणनीतियाँ।",
        mutualFundInvestmentDescription: "उच्च प्रदर्शन वाले म्यूचुअल फंड में निवेश के लिए विशेषज्ञ मार्गदर्शन।",
        financialPlanningDescription: "एक सुरक्षित भविष्य के लिए व्यापक वित्तीय योजना।",
        personalizedAdvisoryDescription: "सूचित निवेश निर्णय लेने में आपकी सहायता के लिए वन-ऑन-वन ​​सलाह।",
        whatIsMutualFundDescription: "म्यूचुअल फंड एक पेशेवर रूप से प्रबंधित निवेश फंड है जो प्रतिभूतियों को खरीदने के लिए कई निवेशकों से धन एकत्र करता है।",
        howToStartInvestingDescription: "रेकमंड के साथ अपनी निवेश यात्रा शुरू करना आसान है। इस पृष्ठ पर दिए गए फॉर्म के माध्यम से या फोन/ईमेल द्वारा हमसे संपर्क करें।",
        risksInvolvedDescription: "सभी म्यूचुअल फंड निवेश बाजार जोखिमों के अधीन हैं। सभी योजना संबंधी दस्तावेजों को ध्यान से पढ़ना महत्वपूर्ण है।",
        personalizedFinancialPlanningDescription: "हां, हम आपके वित्तीय उद्देश्यों को प्राप्त करने में मदद करने के लिए व्यापक और व्यक्तिगत वित्तीय योजना सेवाएं प्रदान करते हैं।",
        yourNamePlaceholder: "आपका नाम",
        yourContactNumberPlaceholder: "आपका संपर्क नंबर",
        subjectOfYourMessagePlaceholder: "आपके संदेश का विषय",
        howCanWeHelpYouPlaceholder: "हम आपकी कैसे मदद कर सकते हैं?"
    },
    mr: {
        services: "सेवा",
        contact: "संपर्क",
        njPortal: "एनजे पोर्टल",
        prudentClientDesk: "प्रुडंट क्लायंट डेस्क",
        fundzBazzarPortal: "फंड्झबाजार पोर्टल",
        amfiindia: "एम्फीइंडिया",
        welcomeToRekmand: "रेकमंड मध्ये आपले स्वागत आहे",
        professionalMutualFundManagement: "व्यावसायिक म्युच्युअल फंड व्यवस्थापन",
        expertMutualFundManagement: "वैयक्तिक सेवेसह तज्ञ म्युच्युअल फंड व्यवस्थापन",
        exploreMutualFunds: "म्युच्युअल फंड शोधा",
        startInvestingToday: "आजच गुंतवणूक सुरू करा",
        marketOverview: "बाजार विहंगावलोकन",
        nifty50: "निफ्टी 50",
        sensex: "सेन्सेक्स",
        niftyMidcap50: "निफ्टी मिडकॅप 50",
        dataDelayNote: "डेटाला 5 मिनिटांचा विलंब असू शकतो. अचूक डेटासाठी, कृपया BSE/NSE वेबसाइटला भेट द्या.",
        top3MutualFunds: "शीर्ष 3 म्युच्युअल फंड",
        investmentTools: "गुंतवणूक साधने",
        sipCalculator: "एसआयपी कॅल्क्युलेटर",
        lumpsumCalculator: "एकमुस्त कॅल्क्युलेटर",
        riskProfiler: "जोखीम प्रोफाइलर",
        goalPlanning: "ध्येय नियोजन",
        calculate: "गणना करा",
        ourServices: "आमच्या सेवा",
        portfolioManagement: "पोर्टफोलिओ व्यवस्थापन",
        mutualFundInvestment: "म्युच्युअल फंड गुंतवणूक",
        financialPlanning: "आर्थिक नियोजन",
        personalizedAdvisory: "वैयक्तिक सल्ला",
        faq: "वारंवार विचारले जाणारे प्रश्न",
        whatIsMutualFund: "म्युच्युअल फंड म्हणजे काय?",
        howToStartInvesting: "रेकमंड सोबत गुंतवणूक कशी सुरू करावी?",
        risksInvolved: "म्युच्युअल फंड गुंतवणुकीत कोणते धोके आहेत?",
        personalizedFinancialPlanning: "तुम्ही वैयक्तिक आर्थिक नियोजन प्रदान करता का?",
        getInTouch: "संपर्क साधा",
        contactInformation: "संपर्क माहिती",
        physicalAddressComingSoon: "भौतिक पत्ता लवकरच येत आहे",
        mapIntegrationComingSoon: "नकाशा एकत्रीकरण लवकरच येत आहे",
        contactForm: "संपर्क फॉर्म",
        name: "नाव",
        contactNumber: "संपर्क क्रमांक",
        subject: "विषय",
        message: "संदेश",
        sendMessage: "संदेश पाठवा",
        allRightsReserved: "सर्व हक्क राखीव.",
        language: "भाषा",
        rekmandName: "रेकमंड",
        njEWealth: "एनजे ई-वेल्थ",
        njClientDesk: "एनजे क्लायंट डेस्क",
        fundzBazzarSignin: "फंड्झबाजार साइनइन",
        fundzBazzarBroking: "फंड्झबाजार ब्रोकिंग",
        keywords: "म्युच्युअल फंड, गुंतवणूक, पोर्टफोलिओ व्यवस्थापन, आर्थिक नियोजन, रेकमंड",
        sipCalculatorDescription: "मासिक एसआयपी गुंतवणुकीतून तुमच्या परताव्याचा अंदाज घ्या.",
        lumpsumCalculatorDescription: "एकमुस्त गुंतवणुकीचे भविष्यकालीन मूल्य मोजा.",
        riskProfilerDescription: "उत्तम गुंतवणूक निर्णयांसाठी तुमच्या जोखीम प्रोफाइलचे मूल्यांकन करा.",
        goalPlanningDescription: "तुमच्या आर्थिक ध्येयांची सहजपणे योजना करा आणि त्यांचा मागोवा घ्या.",
        portfolioManagementDescription: "तुमच्या आर्थिक ध्येयांची पूर्तता करण्यासाठी सानुकूलित पोर्टफोलिओ रणनीती.",
        mutualFundInvestmentDescription: "उच्च कार्यक्षम म्युच्युअल फंडांमध्ये गुंतवणुकीसाठी तज्ञ मार्गदर्शन.",
        financialPlanningDescription: "सुरक्षित भविष्यासाठी व्यापक आर्थिक नियोजन.",
        personalizedAdvisoryDescription: "माहितीपूर्ण गुंतवणूक निर्णय घेण्यासाठी तुम्हाला एक-एक सल्ला.",
        whatIsMutualFundDescription: "म्युच्युअल फंड हा एक व्यावसायिकरित्या व्यवस्थापित गुंतवणूक फंड आहे जो अनेक गुंतवणूकदारांकडून पैसे जमा करून सिक्युरिटीज खरेदी करतो.",
        howToStartInvestingDescription: "रेकमंड सोबत तुमची गुंतवणूक यात्रा सुरू करणे सोपे आहे. या पृष्ठावरील फॉर्मद्वारे किंवा फोन/ईमेलद्वारे आमच्याशी संपर्क साधा.",
        risksInvolvedDescription: "सर्व म्युच्युअल फंड गुंतवणूक बाजारातील जोखमींच्या अधीन आहेत. सर्व योजना संबंधित कागदपत्रे काळजीपूर्वक वाचणे महत्त्वाचे आहे.",
        personalizedFinancialPlanningDescription: "होय, आम्ही तुम्हाला तुमच्या आर्थिक उद्दिष्टे साध्य करण्यात मदत करण्यासाठी व्यापक आणि वैयक्तिक आर्थिक नियोजन सेवा प्रदान करतो.",
        yourNamePlaceholder: "तुमचे नाव",
        yourContactNumberPlaceholder: "तुमचा संपर्क क्रमांक",
        subjectOfYourMessagePlaceholder: "तुमच्या संदेशाचा विषय",
        howCanWeHelpYouPlaceholder: "आम्ही तुम्हाला कशी मदत करू शकतो?"
    },
    gu: {
        services: "સેવાઓ",
        contact: "સંપર્ક",
        njPortal: "એનજે પોર્ટલ",
        prudentClientDesk: "પ્રુડન્ટ ક્લાયન્ટ ડેસ્ક",
        fundzBazzarPortal: "ફંડ્ઝબજાર પોર્ટલ",
        amfiindia: "એમ્ફીઇન્ડિયા",
        welcomeToRekmand: "રેકમંડમાં તમારું સ્વાગત છે",
        professionalMutualFundManagement: "વ્યવસાયિક મ્યુચ્યુઅલ ફંડ વ્યવસ્થાપન",
        expertMutualFundManagement: "વ્યક્તિગત સેવા સાથે નિષ્ણાત મ્યુચ્યુઅલ ફંડ વ્યવસ્થાપન",
        exploreMutualFunds: "મ્યુચ્યુઅલ ફંડ શોધો",
        startInvestingToday: "આજે જ રોકાણ શરૂ કરો",
        marketOverview: "બજાર વિહંગાવલોકન",
        nifty50: "નિફ્ટી 50",
        sensex: "સેન્સેક્સ",
        niftyMidcap50: "નિફ્ટી મિડકેપ 50",
        dataDelayNote: "ડેટામાં 5 મિનિટનો વિલંબ હોઈ શકે છે. સાચા ડેટા માટે, કૃપા કરીને BSE/NSE વેબસાઇટનો સંદર્ભ લો.",
        top3MutualFunds: "ટોચના 3 મ્યુચ્યુઅલ ફંડ",
        investmentTools: "રોકાણ સાધનો",
        sipCalculator: "SIP કેલ્ક્યુલેટર",
        lumpsumCalculator: "લમ્પસમ કેલ્ક્યુલેટર",
        riskProfiler: "જોખમ પ્રોફાઇલર",
        goalPlanning: "લક્ષ્ય આયોજન",
        calculate: "ગણતરી કરો",
        ourServices: "અમારી સેવાઓ",
        portfolioManagement: "પોર્ટફોલિયો વ્યવસ્થાપન",
        mutualFundInvestment: "મ્યુચ્યુઅલ ફંડ રોકાણ",
        financialPlanning: "નાણાકીય આયોજન",
        personalizedAdvisory: "વ્યક્તિગત સલાહ",
        faq: "વારંવાર પૂછાતા પ્રશ્નો",
        whatIsMutualFund: "મ્યુચ્યુઅલ ફંડ શું છે?",
        howToStartInvesting: "રેકમંડ સાથે રોકાણ કેવી રીતે શરૂ કરવું?",
        risksInvolved: "મ્યુચ્યુઅલ ફંડ રોકાણમાં કયા જોખમો શામેલ છે?",
        personalizedFinancialPlanning: "શું તમે વ્યક્તિગત નાણાકીય આયોજન પ્રદાન કરો છો?",
        getInTouch: "સંપર્કમાં રહો",
        contactInformation: "સંપર્ક માહિતી",
        physicalAddressComingSoon: "ભૌતિક સરનામું ટૂંક સમયમાં આવી રહ્યું છે",
        mapIntegrationComingSoon: "નકશા એકીકરણ ટૂંક સમયમાં આવી રહ્યું છે",
        contactForm: "સંપર્ક ફોર્મ",
        name: "નામ",
        contactNumber: "સંપર્ક નંબર",
        subject: "વિષય",
        message: "સંદેશ",
        sendMessage: "સંદેશ મોકલો",
        allRightsReserved: "બધા હકો સુરક્ષિત.",
        language: "ભાષા",
        rekmandName: "રેકમંડ",
        njEWealth: "એનજે ઇ-વેલ્થ",
        njClientDesk: "એનજે ક્લાયન્ટ ડેસ્ક",
        fundzBazzarSignin: "ફંડ્ઝબજાર સાઇનઇન",
        fundzBazzarBroking: "ફંડ્ઝબજાર બ્રોકિંગ",
        keywords: "મ્યુચ્યુઅલ ફંડ, રોકાણ, પોર્ટફોલિયો વ્યવસ્થાપન, નાણાકીય આયોજન, રેકમંડ",
        sipCalculatorDescription: "માસિક SIP રોકાણથી તમારા વળતરનો અંદાજ લગાવો.",
        lumpsumCalculatorDescription: "એક વખતના રોકાણનું ભવિષ્યનું મૂલ્ય ગણતરી કરો.",
        riskProfilerDescription: "વધુ સારા રોકાણ નિર્ણયો માટે તમારી જોખમ પ્રોફાઇલનું મૂલ્યાંકન કરો.",
        goalPlanningDescription: "તમારા નાણાકીય લક્ષ્યોને સરળતાથી આયોજન અને ટ્રૅક કરો.",
        portfolioManagementDescription: "તમારા નાણાકીય લક્ષ્યોને પ્રાપ્ત કરવામાં મદદ કરવા માટે કસ્ટમાઇઝ્ડ પોર્ટફોલિયો વ્યૂહરચના.",
        mutualFundInvestmentDescription: "ટોચના પ્રદર્શન કરતા મ્યુચ્યુઅલ ફંડમાં રોકાણ માટે નિષ્ણાત માર્ગદર્શન.",
        financialPlanningDescription: "સુરક્ષિત ભવિષ્ય માટે વ્યાપક નાણાકીય આયોજન.",
        personalizedAdvisoryDescription: "માહિતીપૂર્ણ રોકાણ નિર્ણયો લેવામાં તમને મદદ કરવા માટે વન-ઓન-वन સલાહ.",
        whatIsMutualFundDescription: "મ્યુચ્યુઅલ ફંડ એ વ્યવસાયિક રીતે સંચાલિત રોકાણ ફંડ છે જે સિક્યોરિટીઝ ખરીદવા માટે ઘણા રોકાણકારો પાસેથી નાણાં એકત્રિત કરે છે.",
        howToStartInvestingDescription: "રેકમંડ સાથે તમારી રોકાણ યાત્રા શરૂ કરવી સરળ છે. આ પૃષ્ઠ પરના ફોર્મ દ્વારા અથવા ફોન/ઇમેઇલ દ્વારા અમારો સંપર્ક કરો.",
        risksInvolvedDescription: "બધા મ્યુચ્યુઅલ ફંડ રોકાણો બજારના જોખમોને આધીન છે. બધા યોજના સંબંધિત દસ્તાવેજો કાળજીપૂર્વક વાંચणे महत्त्वाचे છે.",
        personalizedFinancialPlanningDescription: "હા, અમે તમને તમારા નાણાકીય ઉદ્દેશો પ્રાપ્ત કરવામાં મદદ કરવા માટે વ્યાપક અને વ્યક્તિગત નાણાકીય આયોજન સેવાઓ પ્રદાન કરીએ છીએ.",
        yourNamePlaceholder: "તમારું નામ",
        yourContactNumberPlaceholder: "તમારો સંપર્ક નંબર",
        subjectOfYourMessagePlaceholder: "તમારા સંદેશનો વિષય",
        howCanWeHelpYouPlaceholder: "આપણે તમને કેવી રીતે મદદ કરી શકીએ?"
    },
    ta: {
        services: "சேவைகள்",
        contact: "தொடர்பு",
        njPortal: "என்ஜே போர்டல்",
        prudentClientDesk: "ப்ருடென்ட் கிளையண்ட் டெஸ்க்",
        fundzBazzarPortal: "ஃபண்ட்ஸ்பஜார் போர்டல்",
        amfiindia: "ஆம்ஃபிஇந்தியா",
        welcomeToRekmand: "ரெக்மாண்டிற்கு வரவேற்கிறோம்",
        professionalMutualFundManagement: "தொழில்முறை மியூச்சுவல் ஃபண்ட் மேலாண்மை",
        expertMutualFundManagement: "தனிப்பயனாக்கப்பட்ட சேவையுடன் நிபுணர் மியூச்சுவல் ஃபண்ட் மேலாண்மை",
        exploreMutualFunds: "மியூச்சுவல் ஃபண்டுகளை ஆராயுங்கள்",
        startInvestingToday: "இன்றே முதலீடு செய்யத் தொடங்குங்கள்",
        marketOverview: "சந்தை கண்ணோட்டம்",
        nifty50: "நிஃப்டி 50",
        sensex: "சென்செக்ஸ்",
        niftyMidcap50: "நிஃப்டி மிட்கேப் 50",
        dataDelayNote: "தகவலில் 5 நிமிடம் தாமதம் ஏற்படலாம். சரியான தகவலுக்கு, பிஎஸ்இ/என்எஸ்இ வலைப்பக்கத்தைப் பார்க்கவும்.",
        top3MutualFunds: "சிறந்த 3 மியூச்சுவல் ஃபண்டுகள்",
        investmentTools: "முதலீட்டு கருவிகள்",
        sipCalculator: "SIP கால்குலேட்டர்",
        lumpsumCalculator: "மொத்த தொகை கால்குலேட்டர்",
        riskProfiler: "ஆபத்து சுயவிவரம்",
        goalPlanning: "இலக்கு திட்டமிடல்",
        calculate: "கணக்கிடுங்கள்",
        ourServices: "எங்கள் சேவைகள்",
        portfolioManagement: "போர்ட்ஃபோலியோ மேலாண்மை",
        mutualFundInvestment: "மியூச்சுவல் ஃபண்ட் முதலீடு",
        financialPlanning: "நிதி திட்டமிடல்",
        personalizedAdvisory: "தனிப்பயனாக்கப்பட்ட ஆலோசனை",
        faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
        whatIsMutualFund: "மியூச்சுவல் ஃபண்ட் என்றால் என்ன?",
        howToStartInvesting: "ரெக்மாண்டுடன் முதலீடு செய்வது எப்படி?",
        risksInvolved: "மியூச்சுவல் ஃபண்ட் முதலீடுகளில் உள்ள அபாயங்கள் என்ன?",
        personalizedFinancialPlanning: "நீங்கள் தனிப்பயனாக்கப்பட்ட நிதி திட்டமிடலை வழங்குகிறீர்களா?",
        getInTouch: "தொடர்பில் இருங்கள்",
        contactInformation: "தொடர்பு தகவல்",
        physicalAddressComingSoon: "விரைவில் முகவரி வரும்",
        mapIntegrationComingSoon: "வரைபட ஒருங்கிணைப்பு விரைவில் வருகிறது",
        contactForm: "தொடர்பு படிவம்",
        name: "பெயர்",
        contactNumber: "தொடர்பு எண்",
        subject: "பொருள்",
        message: "செய்தி",
        sendMessage: "செய்தி அனுப்பு",
        allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
        language: "மொழி",
        rekmandName: "ரெக்மாண்ட்",
        njEWealth: "என்ஜே இ-வெல்த்",
        njClientDesk: "என்ஜே கிளையண்ட் டெஸ்க்",
        fundzBazzarSignin: "ஃபண்ட்ஸ்பஜார் சைன்இன்",
        fundzBazzarBroking: "ஃபண்ட்ஸ்பஜார் புரோக்கிங்",
        keywords: "மியூச்சுவல் ஃபண்ட், முதலீடு, போர்ட்ஃபோலியோ மேலாண்மை, நிதி திட்டமிடல், ரெக்மாண்ட்",
        sipCalculatorDescription: "மாதாந்திர SIP முதலீடுகளிலிருந்து உங்கள் வருமானத்தை மதிப்பிடுங்கள்.",
        lumpsumCalculatorDescription: "ஒரு முறை முதலீட்டின் எதிர்கால மதிப்பைக் கணக்கிடுங்கள்.",
        riskProfilerDescription: "சிறந்த முதலீட்டு முடிவுகளுக்கு உங்கள் ஆபத்து சுயவிவரத்தை மதிப்பிடுங்கள்.",
        goalPlanningDescription: "உங்கள் நிதி இலக்குகளை எளிதாக திட்டமிட்டு கண்காணிக்கவும்.",
        portfolioManagementDescription: "உங்கள் நிதி இலக்குகளை அடைய உதவும் தனிப்பயனாக்கப்பட்ட போர்ட்ஃபோலியோ உத்திகள்.",
        mutualFundInvestmentDescription: "சிறந்த செயல்திறன் கொண்ட மியூச்சுவல் ஃபண்டுகளில் முதலீடு செய்வதற்கான நிபுணர் வழிகாட்டுதல்.",
        financialPlanningDescription: "பாதுகாப்பான எதிர்காலத்திற்கான விரிவான நிதி திட்டமிடல்.",
        personalizedAdvisoryDescription: "தகவலறிந்த முதலீட்டு முடிவுகளை எடுக்க உங்களுக்கு உதவும் ஒருவருக்கு ஒருவர் ஆலோசனை.",
        whatIsMutualFundDescription: "மியூச்சுவல் ஃபண்ட் என்பது ஒரு தொழில் ரீதியாக நிர்வகிக்கப்படும் முதலீட்டு நிதியாகும், இது பல முதலீட்டாளர்களிடமிருந்து பணத்தை திரட்டி பத்திரங்களை வாங்குகிறது.",
        howToStartInvestingDescription: "ரெக்மாண்டுடன் உங்கள் முதலீட்டு பயணத்தைத் தொடங்குவது எளிது. இந்தப் பக்கத்தில் உள்ள படிவம் மூலமாகவோ அல்லது தொலைபேசி/மின்னஞ்சல் மூலமாகவோ எங்களைத் தொடர்பு கொள்ளுங்கள்.",
        risksInvolvedDescription: "அனைத்து மியூச்சுவல் ஃபண்ட் முதலீடுகளும் சந்தை அபாயங்களுக்கு உட்பட்டவை. திட்டம் தொடர்பான அனைத்து ஆவணங்களையும் கவனமாகப் படிப்பது முக்கியம்.",
        personalizedFinancialPlanningDescription: "ஆம், உங்கள் நிதி நோக்கங்களை அடைய உதவும் விரிவான மற்றும் தனிப்பயனாக்கப்பட்ட நிதி திட்டமிடல் சேவைகளை நாங்கள் வழங்குகிறோம்.",
        yourNamePlaceholder: "உங்கள் பெயர்",
        yourContactNumberPlaceholder: "உங்கள் தொடர்பு எண்",
        subjectOfYourMessagePlaceholder: "உங்கள் செய்தியின் பொருள்",
        howCanWeHelpYouPlaceholder: "நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?"
    },
    te: {
        services: "సేవలు",
        contact: "సంప్రదించండి",
        njPortal: "ఎన్జె పోర్టల్",
        prudentClientDesk: "ప్రుడెంట్ క్లయింట్ డెస్క్",
        fundzBazzarPortal: "ఫండ్స్‌బజార్ పోర్టల్",
        amfiindia: "యాంఫీఇండియా",
        welcomeToRekmand: "రెక్మాండ్‌కు స్వాగతం",
        professionalMutualFundManagement: "వృత్తిపరమైన మ్యూచువల్ ఫండ్ నిర్వహణ",
        expertMutualFundManagement: "వ్యక్తిగతీకరించిన సేవతో నిపుణుల మ్యూచువల్ ఫండ్ నిర్వహణ",
        exploreMutualFunds: "మ్యూచువల్ ఫండ్లను అన్వేషించండి",
        startInvestingToday: "ఈరోజే పెట్టుబడి పెట్టడం ప్రారంభించండి",
        marketOverview: "మార్కెట్ అవలోకనం",
        nifty50: "నిఫ్టీ 50",
        sensex: "సెన్సెక్స్",
        niftyMidcap50: "నిఫ్టీ మిడ్‌క్యాప్ 50",
        dataDelayNote: "డేటాలో 5 నిమిషాల ఆలస్యం ఉండవచ్చు. సరైన డేటా కోసం, దయచేసి BSE/NSE వెబ్‌పేజీని చూడండి.",
        top3MutualFunds: "టాప్ 3 మ్యూచువల్ ఫండ్‌లు",
        investmentTools: "పెట్టుబడి సాధనాలు",
        sipCalculator: "SIP కాలిక్యులేటర్",
        lumpsumCalculator: "లంప్సమ్ కాలిక్యులేటర్",
        riskProfiler: "రిస్క్ ప్రొఫైలర్",
        goalPlanning: "లక్ష్య ప్రణాళిక",
        calculate: "లెక్కించండి",
        ourServices: "మా సేవలు",
        portfolioManagement: "పోర్ట్‌ఫోలియో నిర్వహణ",
        mutualFundInvestment: "మ్యూచువల్ ఫండ్ పెట్టుబడి",
        financialPlanning: "ఆర్థిక ప్రణాళిక",
        personalizedAdvisory: "వ్యక్తిగతీకరించిన సలహా",
        faq: "తరచుగా అడిగే ప్రశ్నలు",
        whatIsMutualFund: "మ్యూచువల్ ఫండ్ అంటే ఏమిటి?",
        howToStartInvesting: "రెక్మాండ్‌తో పెట్టుబడి పెట్టడం ఎలా ప్రారంభించాలి?",
        risksInvolved: "మ్యూచువల్ ఫండ్ పెట్టుబడులలో ఉన్న నష్టాలు ఏమిటి?",
        personalizedFinancialPlanning: "మీరు వ్యక్తిగతీకరించిన ఆర్థిక ప్రణాళికను అందిస్తున్నారా?",
        getInTouch: "సంప్రదించండి",
        contactInformation: "సంప్రదింపు సమాచారం",
        physicalAddressComingSoon: "భౌతిక చిరునామా త్వరలో వస్తుంది",
        mapIntegrationComingSoon: "మ్యాప్ ఇంటిగ్రేషన్ త్వరలో వస్తుంది",
        contactForm: "సంప్రదింపు ఫారం",
        name: "పేరు",
        contactNumber: "సంప్రదింపు సంఖ్య",
        subject: "విషయం",
        message: "సందేశం",
        sendMessage: "సందేశం పంపండి",
        allRightsReserved: "అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.",
        language: "భాష",
        rekmandName: "రెక్మాండ్",
        njEWealth: "ఎన్జె ఇ-వెల్త్",
        njClientDesk: "ఎన్జె క్లయింట్ డెస్క్",
        fundzBazzarSignin: "ఫండ్స్‌బజార్ సైన్ఇన్",
        fundzBazzarBroking: "ఫండ్స్‌బజార్ బ్రోకింగ్",
        keywords: "మ్యూచువల్ ఫండ్, పెట్టుబడి, పోర్ట్‌ఫోలియో నిర్వహణ, ఆర్థిక ప్రణాళిక, రెక్మాండ్",
        sipCalculatorDescription: "నెలవారీ SIP పెట్టుబడుల నుండి మీ రాబడిని అంచనా వేయండి.",
        lumpsumCalculatorDescription: "ఒకేసారి పెట్టుబడి యొక్క భవిష్యత్తు విలువను లెక్కించండి.",
        riskProfilerDescription: "మెరుగైన పెట్టుబడి నిర్ణయాల కోసం మీ రిస్క్ ప్రొఫైల్‌ను అంచనా వేయండి.",
        goalPlanningDescription: "మీ ఆర్థిక లక్ష్యాలను సులభంగా ప్లాన్ చేయండి మరియు ట్రాక్ చేయండి.",
        portfolioManagementDescription: "మీ ఆర్థిక లక్ష్యాలను సాధించడంలో మీకు సహాయపడటానికి అనుకూలీకరించిన పోర్ట్‌ఫోలియో వ్యూహాలు.",
        mutualFundInvestmentDescription: "అత్యుత్తమ పనితీరు కనబరుస్తున్న మ్యూచువల్ ఫండ్‌లలో పెట్టుబడి పెట్టడానికి నిపుణుల మార్గదర్శకత్వం.",
        financialPlanningDescription: "సురక్షితమైన భవిష్యత్తు కోసం సమగ్ర ఆర్థిక ప్రణాళిక.",
        personalizedAdvisoryDescription: "సమాచారంతో కూడిన పెట్టుబడి నిర్ణయాలు తీసుకోవడంలో మీకు సహాయపడటానికి ఒకరిపై ఒకరు సలహా.",
        whatIsMutualFundDescription: "మ్యూచువల్ ఫండ్ అనేది వృత్తిపరంగా నిర్వహించబడే పెట్టుబడి నిధి, ఇది చాలా మంది పెట్టుబడిదారుల నుండి డబ్బును సమీకరించి సెక్యూరిటీలను కొనుగోలు చేస్తుంది.",
        howToStartInvestingDescription: "రెక్మాండ్‌తో మీ పెట్టుబడి ప్రయాణాన్ని ప్రారంభించడం చాలా సులభం. ఈ పేజీలోని ఫారం ద్వారా లేదా ఫోన్/ఇమెయిల్ ద్వారా మమ్మల్ని సంప్రదించండి.",
        risksInvolvedDescription: "అన్ని మ్యూచువల్ ఫండ్ పెట్టుబడులు మార్కెట్ నష్టాలకు లోబడి ఉంటాయి. పథకానికి సంబంధించిన అన్ని పత్రాలను జాగ్రత్తగా చదవడం ముఖ్యం.",
        personalizedFinancialPlanningDescription: "అవును, మీ ఆర్థిక లక్ష్యాలను సాధించడంలో మీకు సహాయపడటానికి మేము సమగ్రమైన మరియు వ్యక్తిగతీకరించిన ఆర్థిక ప్రణాళిక సేవలను అందిస్తాము.",
        yourNamePlaceholder: "మీ పేరు",
        yourContactNumberPlaceholder: "మీ సంప్రదింపు సంఖ్య",
        subjectOfYourMessagePlaceholder: "మీ సందేశం యొక్క విషయం",
        howCanWeHelpYouPlaceholder: "మేము మీకు ఎలా సహాయపడగలము?"
    },
    bn: {
        services: "পরিষেবা",
        contact: "যোগাযোগ",
        njPortal: "এনজে পোর্টাল",
        prudentClientDesk: "প্রুডেন্ট ক্লায়েন্ট ডেস্ক",
        fundzBazzarPortal: "ফান্ডবাজার পোর্টাল",
        amfiindia: "অ্যামফিইন্ডিয়া",
        welcomeToRekmand: "রেকম্যান্ডে স্বাগতম",
        professionalMutualFundManagement: "পেশাদার মিউচুয়াল ফান্ড ম্যানেজমেন্ট",
        expertMutualFundManagement: "ব্যক্তিগতকৃত পরিষেবা সহ বিশেষজ্ঞ মিউচুয়াল ফান্ড ম্যানেজমেন্ট",
        exploreMutualFunds: "মিউচুয়াল ফান্ড অন্বেষণ করুন",
        startInvestingToday: "আজই বিনিয়োগ শুরু করুন",
        marketOverview: "বাজারের সংক্ষিপ্ত বিবরণ",
        nifty50: "নিফটি 50",
        sensex: "সেনসেক্স",
        niftyMidcap50: "নিফটি মিডক্যাপ 50",
        dataDelayNote: "ডেটাতে 5 মিনিটের বিলম্ব হতে পারে। সঠিক ডেটার জন্য, অনুগ্রহ করে বিএসই/এনএসই ওয়েবপেজ দেখুন।",
        top3MutualFunds: "শীর্ষ 3 মিউচুয়াল ফান্ড",
        investmentTools: "বিনিয়োগ সরঞ্জাম",
        sipCalculator: "এসআইপি ক্যালকুলেটর",
        lumpsumCalculator: "লাম্পসাম ক্যালকুলেটর",
        riskProfiler: "ঝুঁকি প্রোফাইলার",
        goalPlanning: "লক্ষ্য পরিকল্পনা",
        calculate: "হিসাব করুন",
        ourServices: "আমাদের সেবাসমূহ",
        portfolioManagement: "পোর্টফোলিও ম্যানেজমেন্ট",
        mutualFundInvestment: "মিউচুয়াল ফান্ড বিনিয়োগ",
        financialPlanning: "আর্থিক পরিকল্পনা",
        personalizedAdvisory: "ব্যক্তিগতকৃত পরামর্শ",
        faq: "সচরাচর জিজ্ঞাস্য",
        whatIsMutualFund: "মিউচুয়াল ফান্ড কী?",
        howToStartInvesting: "রেকম্যান্ডের সাথে কীভাবে বিনিয়োগ শুরু করবেন?",
        risksInvolved: "মিউচুয়াল ফান্ড বিনিয়োগে কী ঝুঁকি জড়িত?",
        personalizedFinancialPlanning: "আপনি কি ব্যক্তিগতকৃত আর্থিক পরিকল্পনা অফার করেন?",
        getInTouch: "যোগাযোগ করুন",
        contactInformation: "যোগাযোগের তথ্য",
        physicalAddressComingSoon: "শারীরিক ঠিকানা শীঘ্রই আসছে",
        mapIntegrationComingSoon: "মানচিত্র একীকরণ শীঘ্রই আসছে",
        contactForm: "যোগাযোগ ফর্ম",
        name: "নাম",
        contactNumber: "যোগাযোগ নম্বর",
        subject: "বিষয়",
        message: "বার্তা",
        sendMessage: "বার্তা পাঠান",
        allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।",
        language: "ভাষা",
        rekmandName: "রেকম্যান্ড",
        njEWealth: "এনজে ই-ওয়েলথ",
        njClientDesk: "এনজে ক্লায়েন্ট ডেস্ক",
        fundzBazzarSignin: "ফান্ডবাজার সাইনইন",
        fundzBazzarBroking: "ফান্ডবাজার ব্রোকিং",
        keywords: "মিউচুয়াল ফান্ড, বিনিয়োগ, পোর্টফোলিও ম্যানেজমেন্ট, আর্থিক পরিকল্পনা, রেকম্যান্ড",
        sipCalculatorDescription: "মাসিক এসআইপি বিনিয়োগ থেকে আপনার রিটার্ন অনুমান করুন।",
        lumpsumCalculatorDescription: "এককালীন বিনিয়োগের ভবিষ্যত মূল্য গণনা করুন।",
        riskProfilerDescription: "আরও ভাল বিনিয়োগের সিদ্ধান্তের জন্য আপনার ঝুঁকি প্রোফাইল মূল্যায়ন করুন।",
        goalPlanningDescription: "সহজেই আপনার আর্থিক লক্ষ্য পরিকল্পনা এবং ট্র্যাক করুন।",
        portfolioManagementDescription: "আপনার আর্থিক লক্ষ্য অর্জনে সহায়তা করার জন্য কাস্টমাইজড পোর্টফোলিও কৌশল।",
        mutualFundInvestmentDescription: "শীর্ষস্থানীয় মিউচুয়াল ফান্ডে বিনিয়োগের জন্য বিশেষজ্ঞ নির্দেশিকা।",
        financialPlanningDescription: "একটি নিরাপদ ভবিষ্যতের জন্য ব্যাপক আর্থিক পরিকল্পনা।",
        personalizedAdvisoryDescription: "আপনাকে অবগত বিনিয়োগের সিদ্ধান্ত নিতে সহায়তা করার জন্য একের পর এক পরামর্শ।",
        whatIsMutualFundDescription: "একটি মিউচুয়াল ফান্ড হল একটি পেশাগতভাবে পরিচালিত বিনিয়োগ তহবিল যা অনেক বিনিয়োগকারীর কাছ থেকে অর্থ সংগ্রহ করে সিকিউরিটিজ ক্রয় করে।",
        howToStartInvestingDescription: "রেকম্যান্ডের সাথে আপনার বিনিয়োগ যাত্রা শুরু করা সহজ। এই পৃষ্ঠায় ফর্মের মাধ্যমে বা ফোন/ইমেলের মাধ্যমে আমাদের সাথে যোগাযোগ করুন।",
        risksInvolvedDescription: "সমস্ত মিউচুয়াল ফান্ড বিনিয়োগ বাজার ঝুঁকির সাপেক্ষে। সমস্ত স্কিম সম্পর্কিত নথি সাবধানে পড়া গুরুত্বপূর্ণ।",
        personalizedFinancialPlanningDescription: "হ্যাঁ, আমরা আপনাকে আপনার আর্থিক উদ্দেশ্য অর্জনে সহায়তা করার জন্য ব্যাপক এবং ব্যক্তিগতকৃত আর্থিক পরিকল্পনা পরিষেবা সরবরাহ করি।",
        yourNamePlaceholder: "আপনার নাম",
        yourContactNumberPlaceholder: "আপনার যোগাযোগ নম্বর",
        subjectOfYourMessagePlaceholder: "আপনার বার্তার বিষয়",
        howCanWeHelpYouPlaceholder: "আমরা আপনাকে কিভাবে সাহায্য করতে পারি?"
    },
    kn: {
        services: "ಸೇವೆಗಳು",
        contact: "ಸಂಪರ್ಕಿಸಿ",
        njPortal: "ಎನ್ಜೆ ಪೋರ್ಟಲ್",
        prudentClientDesk: "ಪ್ರುಡೆಂಟ್ ಕ್ಲೈಂಟ್ ಡೆಸ್ಕ್",
        fundzBazzarPortal: "ಫಂಡ್ಸ್‌ಬಜಾರ್ ಪೋರ್ಟಲ್",
        amfiindia: "ಅಂಫಿಇಂಡಿಯಾ",
        welcomeToRekmand: "ರೆಕ್ಮಾಂಡ್‌ಗೆ ಸ್ವಾಗತ",
        professionalMutualFundManagement: "ವೃತ್ತಿಪರ ಮ್ಯೂಚುಯಲ್ ಫಂಡ್ ನಿರ್ವಹಣೆ",
        expertMutualFundManagement: "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಸೇವೆಯೊಂದಿಗೆ ತಜ್ಞ ಮ್ಯೂಚುಯಲ್ ಫಂಡ್ ನಿರ್ವಹಣೆ",
        exploreMutualFunds: "ಮ್ಯೂಚುಯಲ್ ಫಂಡ್‌ಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
        startInvestingToday: "ಇಂದೇ ಹೂಡಿಕೆ ಪ್ರಾರಂಭಿಸಿ",
        marketOverview: "ಮಾರುಕಟ್ಟೆ ಅವಲೋಕನ",
        nifty50: "ನಿಫ್ಟಿ 50",
        sensex: "ಸೆನ್ಸೆಕ್ಸ್",
        niftyMidcap50: "ನಿಫ್ಟಿ ಮಿಡ್‌ಕ್ಯಾಪ್ 50",
        dataDelayNote: "ಡೇಟಾದಲ್ಲಿ 5 ನಿಮಿಷಗಳ ವಿಳಂಬವಾಗಬಹುದು. ಸರಿಯಾದ ಡೇಟಾಗಾಗಿ, ದಯವಿಟ್ಟು ಬಿಎಸ್‌ಇ/ಎನ್‌ಎಸ್‌ಇ ವೆಬ್‌ಪೇಜ್ ಅನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        top3MutualFunds: "ಟಾಪ್ 3 ಮ್ಯೂಚುಯಲ್ ಫಂಡ್‌ಗಳು",
        investmentTools: "ಹೂಡಿಕೆ ಉಪಕರಣಗಳು",
        sipCalculator: "ಎಸ್‌ಐಪಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
        lumpsumCalculator: "ಲಂಪ್ಸಮ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
        riskProfiler: "ಅಪಾಯದ ಪ್ರೊಫೈಲರ್",
        goalPlanning: "ಗುರಿ ಯೋಜನೆ",
        calculate: "ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ",
        ourServices: "ನಮ್ಮ ಸೇವೆಗಳು",
        portfolioManagement: "ಪೋರ್ಟ್‌ಫೋಲಿಯೊ ನಿರ್ವಹಣೆ",
        mutualFundInvestment: "ಮ್ಯೂಚುಯಲ್ ಫಂಡ್ ಹೂಡಿಕೆ",
        financialPlanning: "ಹಣಕಾಸು ಯೋಜನೆ",
        personalizedAdvisory: "ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಸಲಹೆ",
        faq: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
        whatIsMutualFund: "ಮ್ಯೂಚುಯಲ್ ಫಂಡ್ ಎಂದರೇನು?",
        howToStartInvesting: "ರೆಕ್ಮಾಂಡ್‌ನೊಂದಿಗೆ ಹೂಡಿಕೆ ಮಾಡುವುದು ಹೇಗೆ?",
        risksInvolved: "ಮ್ಯೂಚುಯಲ್ ಫಂಡ್ ಹೂಡಿಕೆಗಳಲ್ಲಿ ಯಾವ ಅಪಾಯಗಳಿವೆ?",
        personalizedFinancialPlanning: "ನೀವು ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಹಣಕಾಸು ಯೋಜನೆಯನ್ನು ನೀಡುತ್ತೀರಾ?",
        getInTouch: "ಸಂಪರ್ಕದಲ್ಲಿರಿ",
        contactInformation: "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
        physicalAddressComingSoon: "ಭೌತಿಕ ವಿಳಾಸ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
        mapIntegrationComingSoon: "ನಕ್ಷೆ ஒருங்கிணைப்பு ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ",
        contactForm: "ಸಂಪರ್ಕ ಫಾರ್ಮ್",
        name: "ಹೆಸರು",
        contactNumber: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
        subject: "ವಿಷಯ",
        message: "ಸಂದೇಶ",
        sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
        allRightsReserved: "ಎಲ್ಲ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
        language: "ಭಾಷೆ",
        rekmandName: "ರೆಕ್ಮಾಂಡ್",
        njEWealth: "ಎನ್ಜೆ ಇ-ವೆಲ್ತ್",
        njClientDesk: "ಎನ್ಜೆ ಕ್ಲೈಂಟ್ ಡೆಸ್ಕ್",
        fundzBazzarSignin: "ಫಂಡ್ಸ್‌ಬಜಾರ್ ಸೈನ್‌ಇನ್",
        fundzBazzarBroking: "ಫಂಡ್ಸ್‌ಬಜಾರ್ ಬ್ರೋಕಿಂಗ್",
        keywords: "ಮ್ಯೂಚುಯಲ್ ಫಂಡ್, ಹೂಡಿಕೆ, ಪೋರ್ಟ್‌ಫೋಲಿಯೊ ನಿರ್ವಹಣೆ, ಹಣಕಾಸು ಯೋಜನೆ, ರೆಕ್ಮಾಂಡ್",
        sipCalculatorDescription: "ಮಾಸಿಕ ಎಸ್‌ಐಪಿ ಹೂಡಿಕೆಗಳಿಂದ ನಿಮ್ಮ ಆದಾಯವನ್ನು ಅಂದಾಜು ಮಾಡಿ.",
        lumpsumCalculatorDescription: "ಒಂದು ಬಾರಿಯ ಹೂಡಿಕೆಯ ಭವಿಷ್ಯದ ಮೌಲ್ಯವನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಿ.",
        riskProfilerDescription: "ಉತ್ತಮ ಹೂಡಿಕೆ ನಿರ್ಧಾರಗಳಿಗಾಗಿ ನಿಮ್ಮ ಅಪಾಯದ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಿ.",
        goalPlanningDescription: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ಗುರಿಗಳನ್ನು ಸುಲಭವಾಗಿ ಯೋಜಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.",
        portfolioManagementDescription: "ನಿಮ್ಮ ಹಣಕಾಸಿನ ಗುರಿಗಳನ್ನು ಸಾಧಿಸಲು ಸಹಾಯ ಮಾಡಲು ಕಸ್ಟಮೈಸ್ ಮಾಡಿದ ಪೋರ್ಟ್‌ಫೋಲಿಯೊ ತಂತ್ರಗಳು.",
        mutualFundInvestmentDescription: "ಉನ್ನತ ಕಾರ್ಯಕ್ಷಮತೆಯ ಮ್ಯೂಚುಯಲ್ ಫಂಡ್‌ಗಳಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡಲು ತಜ್ಞರ ಮಾರ್ಗದರ್ಶನ.",
        financialPlanningDescription: "ಸುರಕ್ಷಿತ ಭವಿಷ್ಯಕ್ಕಾಗಿ ವ್ಯಾಪಕವಾದ ಹಣಕಾಸು ಯೋಜನೆ.",
        personalizedAdvisoryDescription: "ಮಾಹಿತಿಯುಕ್ತ ಹೂಡಿಕೆ ನಿರ್ಧಾರಗಳನ್ನು ಕೈಗೊಳ್ಳಲು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ಒಬ್ಬರಿಗೊಬ್ಬರು ಸಲಹೆ.",
        whatIsMutualFundDescription: "ಮ್ಯೂಚುಯಲ್ ಫಂಡ್ ಎನ್ನುವುದು ವೃತ್ತಿಪರವಾಗಿ ನಿರ್ವಹించಲ್ಪಡುವ ಹೂಡಿಕೆ ನಿಧಿಯಾಗಿದ್ದು, ಇದು ಅನೇಕ ಹೂಡಿಕೆದಾರರಿಂದ ಹಣವನ್ನು ಸಂಗ್ರಹಿಸಿ ಭದ್ರತೆಗಳನ್ನು ಖರೀದಿಸುತ್ತದೆ.",
        howToStartInvestingDescription: "ರೆಕ್ಮಾಂಡ್‌ನೊಂದಿಗೆ ನಿಮ್ಮ ಹೂಡಿಕೆ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸುವುದು ಸುಲಭ. ಈ ಪುಟದಲ್ಲಿನ ಫಾರ್ಮ್ ಮೂಲಕ ಅಥವಾ ಫೋನ್/ಇಮೇಲ್ ಮೂಲಕ ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ.",
        risksInvolvedDescription: "ಎಲ್ಲಾ ಮ್ಯೂಚುಯಲ್ ಫಂಡ್ ಹೂಡಿಕೆಗಳು ಮಾರುಕಟ್ಟೆಯ ಅಪಾಯಗಳಿಗೆ ಒಳಪಟ್ಟಿರುತ್ತವೆ. ಎಲ್ಲಾ ಸ್ಕೀಮ್ ಸಂಬಂಧಿತ ದಾಖಲೆಗಳನ್ನು ಎಚ್ಚರಿಕೆಯಿಂದ ಓದುವುದು ಮುಖ್ಯ.",
        personalizedFinancialPlanningDescription: "ಹೌದು, ನಿಮ್ಮ ಹಣಕಾಸಿನ ಉದ್ದೇಶಗಳನ್ನು ಸಾಧಿಸಲು ಸಹಾಯ ಮಾಡಲು ನಾವು ವ್ಯಾಪಕವಾದ ಮತ್ತು ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಹಣಕಾಸು ಯೋಜನೆ ಸೇವೆಗಳನ್ನು ಒದಗಿಸುತ್ತೇವೆ.",
        yourNamePlaceholder: "ನಿಮ್ಮ ಹೆಸರು",
        yourContactNumberPlaceholder: "ನಿಮ್ಮ ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
        subjectOfYourMessagePlaceholder: "ನಿಮ್ಮ ಸಂದೇಶದ ವಿಷಯ",
        howCanWeHelpYouPlaceholder: "ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?"
    },
    en_hi: {
        services: "Services",
        contact: "Contact",
        njPortal: "NJ Portal",
        prudentClientDesk: "Prudent Client Desk",
        fundzBazzarPortal: "FundzBazzar Portal",
        amfiindia: "Amfiindia",
        welcomeToRekmand: "Rekmand me aapka swagat hai",
        professionalMutualFundManagement: "Professional Mutual Fund Management",
        expertMutualFundManagement: "Personalized service ke saath expert mutual fund management",
        exploreMutualFunds: "Mutual Funds explore karein",
        startInvestingToday: "Aaj hi invest karna shuru karein",
        marketOverview: "Market ka overview",
        nifty50: "Nifty 50",
        sensex: "Sensex",
        niftyMidcap50: "Nifty Midcap 50",
        dataDelayNote: "Data 5 minute late ho sakta hai. Sahi data ke liye, BSE/NSE webpage dekhein.",
        top3MutualFunds: "Top 3 Mutual Funds",
        investmentTools: "Investment Tools",
        sipCalculator: "SIP Calculator",
        lumpsumCalculator: "Lumpsum Calculator",
        riskProfiler: "Risk Profiler",
        goalPlanning: "Goal Planning",
        calculate: "Calculate",
        ourServices: "Hamari Services",
        portfolioManagement: "Portfolio Management",
        mutualFundInvestment: "Mutual Fund Investment",
        financialPlanning: "Financial Planning",
        personalizedAdvisory: "Personalized Advisory",
        faq: "Aksar puche jaane wale sawal",
        whatIsMutualFund: "Mutual Fund kya hai?",
        howToStartInvesting: "Rekmand ke saath invest kaise karein?",
        risksInvolved: "Mutual fund investments me kya risk hai?",
        personalizedFinancialPlanning: "Kya aap personalized financial planning offer karte hain?",
        getInTouch: "Sampark karein",
        contactInformation: "Contact Information",
        physicalAddressComingSoon: "Physical address jald hi aa raha hai",
        mapIntegrationComingSoon: "Map integration jald hi aa raha hai",
        contactForm: "Contact Form",
        name: "Naam",
        contactNumber: "Contact Number",
        subject: "Subject",
        message: "Message",
        sendMessage: "Message bhejein",
        allRightsReserved: "Sabhi adhikar surakshit hain.",
        language: "Bhasha",
        rekmandName: "Rekmand",
        njEWealth: "NJ E-Wealth",
        njClientDesk: "NJ Client Desk",
        fundzBazzarSignin: "FundzBazzar Signin",
        fundzBazzarBroking: "FundzBazzar Broking",
        keywords: "Mutual Fund, Investment, Portfolio Management, Financial Planning, Rekmand",
        sipCalculatorDescription: "Monthly SIP investments se apne returns ka anuman lagayein.",
        lumpsumCalculatorDescription: "Ek-time investment ki future value calculate karein.",
        riskProfilerDescription: "Behtar investment decisions ke liye apna risk profile assess karein.",
        goalPlanningDescription: "Apne financial goals ko aasani se plan aur track karein.",
        portfolioManagementDescription: "Aapke financial goals achieve karne me madad ke liye customized portfolio strategies.",
        mutualFundInvestmentDescription: "Top-performing mutual funds me invest karne ke liye expert guidance.",
        financialPlanningDescription: "Ek surakshit bhavishya ke liye comprehensive financial planning.",
        personalizedAdvisoryDescription: "Informed investment decisions lene me aapki madad ke liye one-on-one advisory.",
        whatIsMutualFundDescription: "Mutual fund ek professionally managed investment fund hai jo bahut se investors se paise ikattha karke securities kharidta hai.",
        howToStartInvestingDescription: "Rekmand ke saath apni investment journey shuru karna aasan hai. Is page par diye gaye form ke through ya phone/email se humse contact karein.",
        risksInvolvedDescription: "Sabhi mutual fund investments market risks ke adheen hain. Sabhi scheme related documents ko dhyan se padhna zaroori hai.",
        personalizedFinancialPlanningDescription: "Haan, hum aapke financial objectives achieve karne me madad ke liye comprehensive aur personalized financial planning services offer karte hain.",
        yourNamePlaceholder: "Aapka Naam",
        yourContactNumberPlaceholder: "Aapka Contact Number",
        subjectOfYourMessagePlaceholder: "Aapke message ka subject",
        howCanWeHelpYouPlaceholder: "Hum aapki kaise madad kar sakte hain?"
    }
};

let currentLanguage = 'en'; // Default language

function setLanguage(lang) {
    currentLanguage = lang;
    const elements = document.querySelectorAll('[data-lang-key]');
    elements.forEach(element => {
        const key = element.getAttribute('data-lang-key');
        if (translations[currentLanguage][key]) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = translations[currentLanguage][key];
            } else {
                element.textContent = translations[currentLanguage][key];
            }
        }
    });

    // Update specific elements that are not just textContent
    document.querySelector('meta[name="description"]').setAttribute('content', translations[currentLanguage].expertMutualFundManagement);
    document.querySelector('meta[name="keywords"]').setAttribute('content', translations[currentLanguage].keywords);
    document.querySelector('meta[name="author"]').setAttribute('content', "Rekmand"); // Author remains constant
    document.querySelector('meta[property="og:description"]').setAttribute('content', translations[currentLanguage].expertMutualFundManagement);
    document.title = "Rekmand Investment - " + translations[currentLanguage].welcomeToRekmand;

    // Update placeholders - these are now handled by the main loop if data-lang-key is present
    // document.getElementById('name').placeholder = translations[currentLanguage].name;
    // document.getElementById('contact-number').placeholder = translations[currentLanguage].contactNumber;
    // document.getElementById('subject').placeholder = translations[currentLanguage].subject;
    // document.getElementById('message').placeholder = translations[currentLanguage].message;
}

document.addEventListener('DOMContentLoaded', () => {
    // Apply initial language
    setLanguage(currentLanguage);

    // Add event listeners to language options
    const languageDropdownMenu = document.getElementById('language-dropdown-menu');
    if (languageDropdownMenu) {
        languageDropdownMenu.addEventListener('click', (event) => {
            const target = event.target;
            if (target.tagName === 'A' && target.hasAttribute('data-lang')) {
                const lang = target.getAttribute('data-lang');
                setLanguage(lang);
            }
        });
    }
});
